name: Build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    uses: HeavenCube/HCPlugins-actions/.github/workflows/build.yml@main
    with:
      project-name: HCCore
      artifact-path: core-plugin/build/libs/HCCore-*.jar
      publish-gradle-task: ":core-api:publish"
    secrets: inherit
