name: Publish API

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: HeavenCube/HCPlugins-actions/.github/workflows/publish-maven.yml@main
    with:
      gradle-task: ":core-api:publish"
    secrets: inherit
